/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bg.smg.frame;

import bg.smg.util.ImageFilter;
import bg.smg.model.Restaurant;
import bg.smg.model.PricePoint;
import bg.smg.model.Role;
import bg.smg.model.User;
import bg.smg.services.RestaurantService;
import bg.smg.services.UserService;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Natalia
 */



public class AddRestaurantFrame extends javax.swing.JFrame {
    
    private RestaurantService restaurantService;
    private UserService userService;
    private User user;

    /**
     * Creates new form AddRestaurantFrame
     */
    public AddRestaurantFrame(User user) throws SQLException {
        initComponents();
        this.user = user;
        restaurantService = new RestaurantService();
        userService = new UserService();
    }

    private AddRestaurantFrame() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabelPricePoint = new javax.swing.JLabel();
        jButtonAddNewRestaurant = new javax.swing.JButton();
        jComboBoxPricePoint = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setText("Click here to upload image");
        jLabelImage.setToolTipText("");
        jLabelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelImageMousePressed(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jTextFieldName.setText("Enter the restaurant's name");
        jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusLost(evt);
            }
        });
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyPressed(evt);
            }
        });

        jTextFieldAddress.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldAddress.setText("Enter the restaurant's address");
        jTextFieldAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAddressFocusLost(evt);
            }
        });
        jTextFieldAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddressKeyPressed(evt);
            }
        });

        jLabelPricePoint.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabelPricePoint.setText("Choose the price point:");

        jButtonAddNewRestaurant.setBackground(new java.awt.Color(153, 204, 255));
        jButtonAddNewRestaurant.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButtonAddNewRestaurant.setText("Add New Restaurant");
        jButtonAddNewRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewRestaurantActionPerformed(evt);
            }
        });

        jComboBoxPricePoint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxPricePoint.setModel(new DefaultComboBoxModel(bg.smg.model.PricePoint.values()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addComponent(jButtonAddNewRestaurant))
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelPricePoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPricePoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPricePoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxPricePoint, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                    .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonAddNewRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddNewRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewRestaurantActionPerformed
        String name = jTextFieldName.getText();
        String address = jTextFieldAddress.getText();
        PricePoint pricePoint = (PricePoint)jComboBoxPricePoint.getSelectedItem();
        String image = jLabelImage.getIcon().toString();
        image = image.substring(image.indexOf("resources\\restaurant_images\\") + 28);
        Restaurant restaurant = new Restaurant();
        restaurant.setOwnerId(user.getId());
        restaurant.setName(name);
        restaurant.setAddress(address);
        restaurant.setPricePoint(pricePoint);
        restaurant.setImage(image);
        restaurantService.addNewRestaurant(restaurant);
        user.setRole(Role.OWNER);
        userService.changeOwnershipStatus(user);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAddNewRestaurantActionPerformed

    private void jTextFieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyPressed
        if (jTextFieldName.getText().equals("Enter the restaurant's name"))
            jTextFieldName.setText("");
    }//GEN-LAST:event_jTextFieldNameKeyPressed

    private void jTextFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusLost
        if (jTextFieldName.getText().isEmpty()) {
            jTextFieldName.setText("Enter the restaurant's name");
        }
    }//GEN-LAST:event_jTextFieldNameFocusLost

    private void jTextFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusGained
        jTextFieldName.setCaretPosition(0);
    }//GEN-LAST:event_jTextFieldNameFocusGained

    private void jTextFieldAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddressKeyPressed
        if (jTextFieldAddress.getText().equals("Enter the restaurant's address")) {
            jTextFieldAddress.setText("");
        }
    }//GEN-LAST:event_jTextFieldAddressKeyPressed

    private void jTextFieldAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAddressFocusLost
        if (jTextFieldAddress.getText().isEmpty()) {
            jTextFieldAddress.setText("Enter the restaurant's address");
        }
    }//GEN-LAST:event_jTextFieldAddressFocusLost

    private void jTextFieldAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAddressFocusGained
        jTextFieldAddress.setCaretPosition(0);
    }//GEN-LAST:event_jTextFieldAddressFocusGained

    private void jLabelImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImageMousePressed
       JFileChooser fileChooser = new JFileChooser();
       fileChooser.addChoosableFileFilter(new ImageFilter());
       fileChooser.setAcceptAllFileFilterUsed(false);
       
       int result = fileChooser.showOpenDialog(this);
       if(result == JFileChooser.APPROVE_OPTION){
           File selectedFile = fileChooser.getSelectedFile();
		    ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
		    Image image = imageIcon.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(),
			    Image.SCALE_SMOOTH);
		    imageIcon.setImage(image);
		    jLabelImage.setIcon(imageIcon);
		    jLabelImage.setText("");
       }
    }//GEN-LAST:event_jLabelImageMousePressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(AddRestaurantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(AddRestaurantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(AddRestaurantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(AddRestaurantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new AddRestaurantFrame().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewRestaurant;
    private javax.swing.JComboBox<String> jComboBoxPricePoint;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelPricePoint;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
